### ISSUE TITLE
Some question about the Config II_BESS_CSC

### ISSUE THREAD

**Issue by Pandora-trex** [DESL-EPFL/Extension-of-the-IEEE-39-bus-Test-Networkfor-the-Study-of-Fundamental-Dynamicsof-Modern-Power-System#1]
First of all, thank you for your impressive work. The battery energy storage system in IEEE config II _BESS_CSC simulation seems inconsistent with the descriptions of Report PDF file (Figure 6 in Section 1.5.1). How to use the three time constant equivalent circuit in the simulink?

**Comment by Yihuiz** [comment]
Hi, thanks for interesting in this work. So, the three-time constant model equivalent circuit is used to model the output voltage of battery.  There are several ways to model it in simulink. It is possible to build an equivalent circuit as in Figure 6 using Simulink electrical blocks. However, the parameters R, L C and the open circuit voltage E are all SOC dependent, which means you have to change those parameters on-fly based SOC variation. To deal with this modeling hurdle, we directly use a state-space model (which is an exact replicate of the electrical circuit) to compute battery output voltage.

**Comment by Pandora-trex** [comment]
Thanks
